services:
  postgresDB:
    image: postgres:16
    container_name: postgresDB
    ports:
      - "5432:5432"
    restart: always
    environment:
       POSTGRES_USER: "mydsa"
       POSTGRES_PASSWORD: "dsachoice"
       POSTGRES_DB: "agendamento_tarefas"
    volumes:
      - sys-db-agedamento:/var/postgresql/data

  api-tarefas:
    build: .
    image: sys_agedamento_tarefa:0.1
    ports:
      - "5181:5181"
    environment:
       ASPNETCORE_ENVIRONMENT: Development
    depends_on: 
      - postgresDB
    command: 
    
volumes:
  sys-db-agedamento:
     name: db_agendamento